{
  "jobs":
    {
      "default_stage_matrix":
        {
          "container": "groupsinfra/gocd-agent-centos-8-groups:docker-gocd-agent-centos-8-groups_84b71558.15",
          "runs-on": "ubuntu-20.04",
          "steps": [{ "run": "ls" }],
          "strategy":
            {
              "matrix":
                {
                  "platform_name":
                    [
                      { "name": "windows" },
                      { "name": "linux" },
                      { "name": "web" },
                    ],
                },
            },
        },
    },
  "on": ["push"],
}
