{
  "jobs":
    {
      "container": "groupsinfra:docker-gocd-agent-centos-8-groups_84b71558.15",
      "default_stage_matrix":
        {
          "steps": [{ "run": "ls" }],
          "strategy":
            {
              "matrix":
                {
                  "platform_name":
                    [
                      { "name": "windowsJob" },
                      { "name": "linuxJob" },
                      { "name": "webJob" },
                    ],
                },
            },
        },
    },
  "on": ["push"],
}
