{
  "defaults": { "run": { "working-directory": "/home/go" } },
  "env": { "GODOT_STATUS": "groups-4.0.0" },
  "jobs":
    {
      "default_stage_matrix":
        {
          "container": "groupsinfra/gocd-agent-centos-8-groups:docker-gocd-agent-centos-8-groups_84b71558.15",
          "runs-on": "ubuntu-20.04",
          "steps":
            [
              {
                "name": "Checkout tools repo",
                "uses": "actions/checkout@v3",
                "with":
                  {
                    "path": "/home/go/g",
                    "ref": "groups-4.x",
                    "repository": "V-Sekai/godot.git",
                  },
              },
              {
                "name": "Checkout Godot Custom Modules",
                "uses": "actions/checkout@v3",
                "with":
                  {
                    "path": "/home/go/godot_custom_modules",
                    "ref": "groups-modules-4.x",
                    "repository": "V-Sekai/godot-modules-groups.git",
                  },
              },
              {
                "run": "sed -i \"/^status =/s/=.*/= \\\"$GODOT_STATUS.$GO_PIPELINE_COUNTER\\\"/\" version.py",
                "working-directory": "/home/go/g",
              },
              {
                "run": "${{ matrix.platform_name.scons_env }} scons werror=no platform=${{ matrix.platform_name.scons_platform }} target=release_debug -j`nproc` use_lto=no deprecated=no ${{ matrix.platform_name.scons_arguments }} custom_modules=../godot_custom_modules",
                "working-directory": "/home/go/g",
              },
              {
                "if": true,
                "run": "cp -p g/bin/' + ${{  matrix.platform_name.intermediate_godot_binary }} + ' g/bin/' + ${{ matrix.platform_name.editor_godot_binary }} ",
              },
            ],
          "strategy":
            {
              "matrix":
                {
                  "platform_name":
                    [
                      {
                        "editor_godot_binary": "godot.windows.opt.tools.64.exe",
                        "intermediate_godot_binary": "godot.windows.opt.tools.64.exe",
                        "name": "windows",
                        "scons_env": "PATH=/opt/llvm-mingw/bin:$PATH ",
                        "scons_platform": "windows",
                      },
                      {
                        "editor_godot_binary": "godot.linuxbsd.opt.tools.64.llvm",
                        "intermediate_godot_binary": "godot.linuxbsd.opt.tools.64.llvm",
                        "name": "linux",
                        "scons_env": "",
                        "scons_platform": "linuxbsd",
                      },
                      {
                        "editor_godot_binary": "godot.javascript.opt.debug.threads.zip",
                        "intermediate_godot_binary": "godot.javascript.opt.debug.threads.zip",
                        "name": "web",
                        "scons_env": "source /opt/emsdk/emsdk_env.sh && EM_CACHE=/tmp ",
                        "scons_platform": "javascript",
                      },
                    ],
                },
            },
        },
    },
  "on": ["push"],
}
